# Generated by Django 5.0.6 on 2024-06-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor')], max_length=20)),
                ('nivel', models.CharField(choices=[('nivel_inicial', 'Nivel Inicial'), ('educacion_basica', 'Educación Básica'), ('educacion_media', 'Educación Media')], max_length=100)),
                ('ciclo', models.CharField(choices=[('preescolar', 'Preescolar'), ('ciclo_1', 'Ciclo 1'), ('ciclo_2', 'Ciclo 2'), ('ciclo_3', 'Ciclo 3'), ('bachillerato', 'Bachillerato')], max_length=100)),
                ('especializacion', models.CharField(blank=True, choices=[('BTI', 'BTI'), ('BATAN', 'BATAN'), ('ciencias_basicas', 'Ciencias Básicas'), ('ciencias_sociales', 'Ciencias Sociales')], max_length=100, null=True)),
                ('grado_curso', models.CharField(choices=[('pre-jardin', 'Pre-jardín'), ('jardin', 'Jardín'), ('preescolar', 'Preescolar'), ('primer_grado', 'Primer Grado'), ('segundo_grado', 'Segundo Grado'), ('tercer_grado', 'Tercer Grado'), ('cuarto_grado', 'Cuarto Grado'), ('quinto_grado', 'Quinto Grado'), ('sexto_grado', 'Sexto Grado'), ('septimo_grado', 'Séptimo Grado'), ('octavo_grado', 'Octavo Grado'), ('noveno_grado', 'Noveno Grado'), ('primer_curso', 'Primer Curso'), ('segundo_curso', 'Segundo Curso'), ('tercer_curso', 'Tercer Curso')], max_length=100)),
                ('matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.alumno')),
                ('responsables', models.ManyToManyField(to='StudentApp.responsable')),
            ],
        ),
    ]
